In [1]:
# require(data.table)
# require(bit64)
# require(dbscan)
# require(doParallel)
# require(rBayesianOptimization)
# path='../input/train_1/'
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

from trackml.dataset import load_event, load_dataset
from trackml.score import score_event
from trackml.randomize import shuffle_hits

from sklearn.preprocessing import StandardScaler
import hdbscan as _hdbscan
from scipy import stats
from tqdm import tqdm

import time

from sklearn.cluster.dbscan_ import dbscan
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KDTree
import hdbscan
from bayes_opt import BayesianOptimization

# https://www.ellicium.com/python-multiprocessing-pool-process/
# http://sebastianraschka.com/Articles/2014_multiprocessing.html
from multiprocessing import Pool

In [2]:
import os
import time
import hdbscan as _hdbscan
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

In [3]:
def create_one_event_submission(event_id, hits, labels):
    sub_data = np.column_stack(([event_id]*len(hits), hits.hit_id.values, labels))
    submission = pd.DataFrame(data=sub_data, columns=["event_id", "hit_id", "track_id"]).astype(int)
    return submission

In [4]:
def preprocess(hits):        
    x = hits.x.values
    y = hits.y.values
    z = hits.z.values

    r = np.sqrt(x**2 + y**2 + z**2)
    hits['x2'] = x/r
    hits['y2'] = y/r

    r = np.sqrt(x**2 + y**2)
    hits['z2'] = z/r

    ss = StandardScaler()
    X = ss.fit_transform(hits[['x2', 'y2', 'z2']].values)
#     for i, rz_scale in enumerate(self.rz_scales):
#         X[:,i] = X[:,i] * rz_scale

    return X

In [5]:
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

#------------------------------------------------------

def make_counts(labels):
    
    
    _,reverse,count = np.unique(labels,return_counts=True,return_inverse=True)
    counts = count[reverse]
    counts[labels==0]=0
    
    return counts

def one_loop(param):
    
    # <todo> tune your parameters or design your own features here! 
    
    i,m, x,y,z, d,r, a, a_start,a_step = param
    #print('\r %3d  %+0.8f '%(i,da), end='', flush=True)
    
    da = m*(a_start - (i*a_step))
    aa = a + np.sign(z)*z*da 
    zr = z/r
    
    X = StandardScaler().fit_transform(np.column_stack([aa, aa/zr, zr, 1/zr, aa/zr + 1/zr]))
    _,l = dbscan(X, eps=0.0035, min_samples=1,)

    return l

def one_loop1(param):
    
    # <todo> tune your parameters or design your own features here! 
    
    i,m, x,y,z, d,r,r2,z2,a, a_start,a_step = param
    #print('\r %3d  %+0.8f '%(i,da), end='', flush=True)
    
    da = m*(a_start - (i*a_step))
    aa = a + np.sign(z)*z*da
#     if m == 1:
#         print(da)
    zr = z/r # this is cot(theta), 1/zr is tan(theta)
    theta = np.arctan2(r, z)
    ct = np.cos(theta)
    st = np.sin(theta)
    tt = np.tan(theta)
#     ctt = np.cot(theta)
    z2r = z2/r
    z2r2 = z2/r2
#     X = StandardScaler().fit_transform(df[['r2', 'theta_1', 'dip_angle', 'z2', 'z2_1', 'z2_2']].values)

    caa = np.cos(aa)
    saa = np.sin(aa)
    taa = np.tan(aa)
    ctaa = 1/taa
    
#     0.000005
    deps = 0.0000025
    X = StandardScaler().fit_transform(np.column_stack([caa, saa, tt, 1/tt]))
    l= DBSCAN(eps=0.0035+i*deps,min_samples=1,metric='euclidean',n_jobs=8).fit(X).labels_
#     _,l = dbscan(X, eps=0.0035, min_samples=1,algorithm='auto')
    
    return l

def one_loop2(param):
    
    # <todo> tune your parameters or design your own features here! 
    
    i,m, x,y,z, d,r,r2,z2,a, a_start,a_step = param
    #print('\r %3d  %+0.8f '%(i,da), end='', flush=True)
    
    da = m*(a_start - (i*a_step))
    aa = a + np.sign(z)*z*da
#     if m == 1:
#         print(da)
    zr = z/r # this is cot(theta), 1/zr is tan(theta)
    theta = np.arctan2(r, z)
    ct = np.cos(theta)
    st = np.sin(theta)
    tt = np.tan(theta)
#     ctt = np.cot(theta)
    z2r = z2/r
    z2r2 = z2/r2
#     X = StandardScaler().fit_transform(df[['r2', 'theta_1', 'dip_angle', 'z2', 'z2_1', 'z2_2']].values)

    caa = np.cos(aa)
    saa = np.sin(aa)
    taa = np.tan(aa)
    ctaa = 1/taa
    
#     0.000005
    deps = 0.0000025
    X = StandardScaler().fit_transform(np.column_stack([caa, saa, tt, 1/tt]))
    l= DBSCAN(eps=0.0035+i*deps,min_samples=1,metric='euclidean',n_jobs=8).fit(X).labels_
#     _,l = dbscan(X, eps=0.0035, min_samples=1,algorithm='auto')
    
    return l

def do_dbscan_predict(df):
    
    x  = df.x.values
    y  = df.y.values
    z  = df.z.values
    r  = np.sqrt(x**2+y**2)
    d  = np.sqrt(x**2+y**2+z**2)
    a  = np.arctan2(y,x)

    x2 = df['x']/d
    y2 = df['y']/d
    z2 = df['z']/r

    r2 = np.sqrt(x2**2 + y2**2)
    phi = np.arctan2(y, x)
    phi_deg= np.degrees(np.arctan2(y, x))
    phi2 = np.arctan2(y2, x2)
    phi2_deg = np.degrees(np.arctan2(y2, x2))
    
    
    scores = []

    a_start,a_step,a_num = 0.00100,0.0000095,150

    params  = [(i,m, x,y,z,d,r,r2,z2, a, a_start,a_step) for i in range(a_num) for m in [-1,1]]

    if 1: 
        pool = Pool(processes=1)
        ls   = pool.map( one_loop1, params )


    if 0:
        ls = [ one_loop(param) for param in  params ]


    ##------------------------------------------------

    num_hits=len(df)
    labels = np.zeros(num_hits,np.int32)
    counts = np.zeros(num_hits,np.int32)
    for l in ls:
        c = make_counts(l)
        idx = np.where((c-counts>0) & (c<20))[0]
        labels[idx] = l[idx] + labels.max()
        counts = make_counts(labels)
       

#     cl = hdbscan.HDBSCAN(min_samples=1,min_cluster_size=7,
#                          metric='braycurtis',cluster_selection_method='leaf',algorithm='best', 
#                          leaf_size=50)
    
#     X = preprocess(df)
#     l1 = pd.Series(labels)
#     labels = np.unique(l1)
   
# #   print(X.shape)
# #   print(len(labels_org))
# #   print(len(labels_org[labels_org ==0]))
# #   print(len(labels_org[labels_org ==-1]))
    
#     n_labels = 0
#     while n_labels < len(labels):
#         n_labels = len(labels)
#         max_len = np.max(l1)
#         s = list(l1[l1 == 0].keys())
#         X = X[s]
#         print(X.shape)
#         if X.shape[0] <= 1:
#             break
#         l = cl.fit_predict(X)+max_len
# #         print(len(l))
#         l1[l1 == 0] = l
#         labels = np.unique(l1)
    
    return labels

## reference----------------------------------------------
def do_dbscan0_predict(df):
    x = df.x.values
    y = df.y.values
    z = df.z.values
    r = np.sqrt(x**2+y**2)
    d = np.sqrt(x**2+y**2+z**2)

    X = StandardScaler().fit_transform(np.column_stack([
        x/d, y/d, z/r]))
    _,labels = dbscan(X,
                eps=0.0075,
                min_samples=1,
                algorithm='auto',
                n_jobs=-1)

    #labels = hdbscan(X, min_samples=1, min_cluster_size=5, cluster_selection_method='eom')

    return labels

## reference----------------------------------------------
def do_dbscan0_predict(df):
    x = df.x.values
    y = df.y.values
    z = df.z.values
    r = np.sqrt(x**2+y**2)
    d = np.sqrt(x**2+y**2+z**2)

    X = StandardScaler().fit_transform(np.column_stack([
        x/d, y/d, z/r]))
    _,labels = dbscan(X,
                eps=0.0075,
                min_samples=1,
                algorithm='auto',
                n_jobs=-1)

    #labels = hdbscan(X, min_samples=1, min_cluster_size=5, cluster_selection_method='eom')

    return labels
var1 = 0
def extend(submission,hits):
    df = submission.merge(hits,  on=['hit_id'], how='left')
#     if var1 != 0:
#         df = submission.merge(hits,  on=['hit_id'], how='left')
#     else:
#         df = hits
#     df = submission.append(hits)
#     print(df.head())
    df = df.assign(d = np.sqrt( df.x**2 + df.y**2 + df.z**2 ))
    df = df.assign(r = np.sqrt( df.x**2 + df.y**2))
    df = df.assign(arctan2 = np.arctan2(df.z, df.r))

    for angle in range(-180,180,1):

        print ('\r %f'%angle, end='',flush=True)
        #df1 = df.loc[(df.arctan2>(angle-0.5)/180*np.pi) & (df.arctan2<(angle+0.5)/180*np.pi)]
        df1 = df.loc[(df.arctan2>(angle-1.0)/180*np.pi) & (df.arctan2<(angle+1.0)/180*np.pi)]

#         if len(df1) == 0:
#             continue
        min_num_neighbours = len(df1)
        if min_num_neighbours<4: continue

        hit_ids = df1.hit_id.values
        x,y,z = df1.as_matrix(columns=['x', 'y', 'z']).T
        r  = (x**2 + y**2)**0.5
        r  = r/1000
        a  = np.arctan2(y,x)
        tree = KDTree(np.column_stack([a,r]), metric='euclidean')

#         print(df1.head())
        track_ids = list(df1.track_id.unique())
        num_track_ids = len(track_ids)
        min_length=3

        for i in range(num_track_ids):
            p = track_ids[i]
            if p==0: continue

            idx = np.where(df1.track_id==p)[0]
            if len(idx)<min_length: continue

            if angle>0:
                idx = idx[np.argsort( z[idx])]
            else:
                idx = idx[np.argsort(-z[idx])]


            ## start and end points  ##
            idx0,idx1 = idx[0],idx[-1]
            a0 = a[idx0]
            a1 = a[idx1]
            r0 = r[idx0]
            r1 = r[idx1]

            da0 = a[idx[1]] - a[idx[0]]  #direction
            dr0 = r[idx[1]] - r[idx[0]]
            direction0 = np.arctan2(dr0,da0) 

            da1 = a[idx[-1]] - a[idx[-2]]
            dr1 = r[idx[-1]] - r[idx[-2]]
            direction1 = np.arctan2(dr1,da1) 


            ## extend start point
            ns = tree.query([[a0,r0]], k=min(20,min_num_neighbours), return_distance=False)
            ns = np.concatenate(ns)
            direction = np.arctan2(r0-r[ns],a0-a[ns])
            ns = ns[(r0-r[ns]>0.01) &(np.fabs(direction-direction0)<0.04)]

            for n in ns:
                df.loc[ df.hit_id==hit_ids[n],'track_id' ] = p 

            ## extend end point
            ns = tree.query([[a1,r1]], k=min(20,min_num_neighbours), return_distance=False)
            ns = np.concatenate(ns)

            direction = np.arctan2(r[ns]-r1,a[ns]-a1)
            ns = ns[(r[ns]-r1>0.01) &(np.fabs(direction-direction1)<0.04)] 

            for n in ns:
                df.loc[ df.hit_id==hit_ids[n],'track_id' ] = p
    #print ('\r')
#     df = df[['particle_id', 'weight', 'event_id', 'hit_id', 'track_id']]
    df = df[['event_id', 'hit_id', 'track_id']]
    return df

In [6]:
def trackML(df, w1, w2, w3, Niter):
    x  = df.x.values
    y  = df.y.values
    z  = df.z.values
    rt  = np.sqrt(x**2+y**2)
    r  = np.sqrt(x**2+y**2+z**2)
    a0  = np.arctan2(y,x)

    
    phi = np.arctan2(y, x)
    phi_deg= np.degrees(np.arctan2(y, x))
    
    
    z1 = z/rt
    z2 = z/r
    
    theta = np.arctan2(rt, z)
    tt = np.tan(theta)
    
    z3 = np.log1p(abs(z/r))*np.sign(z)
    
    mm = 1
    ls = []
    print(Niter)
    Niter = Niter.astype(np.int32)
    print(Niter)
    print(w1, w2, w3, Niter)
    for ii in range(Niter):
        mm = mm * (-1)
#         print(np.pi)
        a1 = a0+mm*(rt+0.0000075*rt**2)/1000*(ii/2)/180*np.pi
#         a1 = a0 + mm*(rt+0.000005*rt**2)/1000*(ii)/180*np.pi
#         print(a0, a1)
        saa = np.sin(a1)
        caa = np.cos(a1)
        
        deps = 0.0000025
#         X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2, x/y, x/rt , y/rt]))
        X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2, x/y]))
#         print(X.shape)
        
        cx = [w1,w1,w2,w3,w3]
        for jj in range(X.shape[1]): 
             X[:,jj] = X[:,jj]*cx[jj]
        l= DBSCAN(eps=0.0035,min_samples=1,metric='euclidean',n_jobs=8).fit(X).labels_
        ls.append(l)
        
    num_hits=len(df)
    labels = np.zeros(num_hits,np.int32)
    counts = np.zeros(num_hits,np.int32)
    for l in ls:
        c = make_counts(l)
        idx = np.where((c-counts>0) & (c<20))[0]
        labels[idx] = l[idx] + labels.max()
        counts = make_counts(labels)
        
    return labels

In [7]:
def trackML2(df, w1, w2, w3, Niter):
    x  = df.x.values
    y  = df.y.values
    z  = df.z.values
    rt  = np.sqrt(x**2+y**2)
    r  = np.sqrt(x**2+y**2+z**2)
    a0  = np.arctan2(y,x)

    
    phi = np.arctan2(y, x)
    phi_deg= np.degrees(np.arctan2(y, x))
    
    
    z1 = z/rt
    z2 = z/r
    
    theta = np.arctan2(rt, z)
    tt = np.tan(theta)
    
    mm = 1
    ls = []
    
    for ii in range(Niter):
        mm = mm * (-1)
#         print(np.pi)
        a1 = a0+mm*(rt+0.000005*rt**2)/1000*(ii/2)/180*np.pi
#         print(a0, a1)
        saa = np.sin(a1)
        caa = np.cos(a1)
        
        deps = 0.0000025
        X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2]))
#         print(X.shape)
        
        cx = [w1,w1,w2,w3]
        for jj in range(X.shape[1]): 
             X[:,jj] = X[:,jj]*cx[jj]
        l= DBSCAN(eps=0.0035,min_samples=1,metric='euclidean',n_jobs=8).fit(X).labels_
        ls.append(l)
        
    num_hits=len(df)
    labels = np.zeros(num_hits,np.int32)
    counts = np.zeros(num_hits,np.int32)
    for l in ls:
        c = make_counts(l)
        idx = np.where((c-counts>0) & (c<20))[0]
        labels[idx] = l[idx] + labels.max()
        counts = make_counts(labels)
        
    return labels

In [8]:
def trackML3(df, w1, w2, w3, w4, w5, w6, w7, Niter):
    x  = df.x.values
    y  = df.y.values
    z  = df.z.values
    
    dz = 0
    z = z + dz
    
    rt  = np.sqrt(x**2+y**2)
    r  = np.sqrt(x**2+y**2+z**2)
    a0  = np.arctan2(y,x)

    
    phi = np.arctan2(y, x)
    phi_deg= np.degrees(np.arctan2(y, x))
    
    
    z1 = z/rt
    z2 = z/r
    
    x2 = x/r
    y2 = y/r
    z22 = z/rt
    
    rt2 = np.sqrt(x2**2 + y2**2)
    r2 = np.sqrt(x2**2 + y2**2 + z2**2)
    
    theta = np.arctan2(rt, z)
#     theta = np.arctan2(rt2, z2)
    tt = np.tan(theta)
    ctt = np.cos(theta)
    stt = np.sin(theta)

    mm = 1
    ls = []
    
#     x/y；x/rt ; y/rt

#     print(Niter)
#     Niter = Niter.astype(np.int32)
#     print(Niter)
#     print(w1, w2, w3, Niter)
    
    for ii in range(Niter):
        mm = mm * (-1)
#         print(np.pi)
#         a1 = a0+mm*(rt+0.000045*rt**2)/1000*(ii/2)/180*np.pi
        a1 = a0+mm*(rt+0.0000075*rt**2)/1000*(ii/2)/180*np.pi
    
        xx1 = a1/z1
        xx2 = 1/z1
    
#         print(a0, a1)
        saa = np.sin(a1)
        caa = np.cos(a1)
        
        deps = 0.0000025
        c1 = caa*stt
        c2 = saa*ctt
#         c3 = (ctt+stt)/(ctt-stt)
        X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2, rt/r, xx1, xx2]))
#         print(X.shape)
        
        cx = [w1,w1,w2,w3, w4, w6, w7]
        for jj in range(X.shape[1]): 
             X[:,jj] = X[:,jj]*cx[jj]
        deps = 0.0000025
        l= DBSCAN(eps=0.0035,min_samples=1,metric='euclidean',n_jobs=8).fit(X).labels_
        ls.append(l)
    
#     for ii in range(Niter):
#         mm = mm * (1)
# #         print(np.pi)
#         a1 = a0+mm*(rt+0.000005*rt**2)/1000*(ii/2)/180*np.pi
# #         print(a0, a1)
#         saa = np.sin(a1)
#         caa = np.cos(a1)
        
#         deps = 0.0000025
#         X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2]))
# #         print(X.shape)
        
#         cx = [w1,w1,w2,w3]
#         for jj in range(X.shape[1]): 
#              X[:,jj] = X[:,jj]*cx[jj]
#         deps = 0.0000025
#         l= DBSCAN(eps=0.0035+ii*deps,min_samples=1,metric='euclidean',n_jobs=8).fit(X).labels_
#         ls.append(l)
        
    num_hits=len(df)
    labels = np.zeros(num_hits,np.int32)
    counts = np.zeros(num_hits,np.int32)
    for l in ls:
        c = make_counts(l)
        idx = np.where((c-counts>0) & (c<20))[0]
        labels[idx] = l[idx] + labels.max()
        counts = make_counts(labels)
        
    return labels

In [9]:
import hdbscan
def trackML31(df, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, Niter):
    x  = df.x.values
    y  = df.y.values
    z  = df.z.values
    
    dz = 0
    z = z + dz
    
    rt  = np.sqrt(x**2+y**2)
    r  = np.sqrt(x**2+y**2+z**2)
    a0  = np.arctan2(y,x)

    x2 = x/r
    y2 = y/r
    
    
    phi = np.arctan2(y, x)
    phi_deg= np.degrees(np.arctan2(y, x))
    
    
    z1 = z/rt
    z2 = z/r
    
    z3 = np.log1p(abs(z/r))*np.sign(z)
    
    x1 = x/rt
    y1 = y/rt
    
    y3 = np.log1p(abs(y/r))*np.sign(y)
    
    theta = np.arctan2(rt, z)
    theta_deg = np.degrees(np.arctan2(rt, z))
    tt = np.tan(theta_deg)
    
    z4 = np.sqrt(abs(z/rt))
    
    x4 = np.sqrt(abs(x/r))
    y4 = np.sqrt(abs(y/r))
    
    mm = 1
    ls = []
    
#     print(Niter)
#     Niter = Niter.astype(np.int32)
#     print(Niter)
#     print(w1, w2, w3, Niter)
    
    for ii in range(Niter):
        mm = mm * (-1)
#         print(np.pi)
#         a1 = a0+mm*(rt+0.000045*rt**2)/1000*(ii/2)/180*np.pi
#         a1 = a0+mm*(rt+0.0000075*rt**2)/1000*(ii/2)/180*np.pi
        a1 = a0+mm*(rt+ 0.0000145*rt**2)/1000*(ii/2)/180*np.pi
#         print(a0, a1)
        saa = np.sin(a1)
        caa = np.cos(a1)
        
        t1 = theta+mm*(rt+ 0.8435*rt**2)/1000*(ii/2)/180*np.pi
        ctt = np.cos(t1)
        stt = np.sin(t1)
        ttt = np.tan(t1)
        deps = 0.0000025
#         X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2, rt/r, x/r, z3, ctt, stt]))
        X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2, rt/r, x/r, y/r, z3, y1, y3, 
                                                            ctt, stt, z4, x4]))
#         print(X.shape)
        
#         cx = [w1,w1,w2,w3, w4, w5, w6, w7, w7]
        cx = [w1,w1,w2,w3, w4, w5, w6, w7, w8, w9, w10, w10, w11, w12]
        for jj in range(X.shape[1]): 
             X[:,jj] = X[:,jj]*cx[jj]
        deps = 0.0000025
#         cl = hdbscan.HDBSCAN(min_samples=1,min_cluster_size=7,cluster_selection_method='leaf',metric='euclidean', leaf_size=50)
#         l = cl.fit_predict(X)+1
        
        l= DBSCAN(eps=0.0035,min_samples=1,metric='euclidean',n_jobs=8).fit(X).labels_
#         l= DBSCAN(eps=w7,min_samples=1,metric='euclidean',n_jobs=8).fit(X).labels_
        ls.append(l)
    
    
    num_hits=len(df)
    labels = np.zeros(num_hits,np.int32)
    counts = np.zeros(num_hits,np.int32)
    for l in ls:
        c = make_counts(l)
        idx = np.where((c-counts>0) & (c<20))[0]
        labels[idx] = l[idx] + labels.max()
        counts = make_counts(labels)
        
    return labels

In [10]:
######################## 
### working function ###
# ########################
# trackML <- function(dfh,w1,w2,w3,Niter){
#   dfh[,s1:=hit_id]
#   dfh[,N1:=1L] 
#   dfh[,r:=sqrt(x*x+y*y+z*z)]
#   dfh[,rt:=sqrt(x*x+y*y)]
#   dfh[,a0:=atan2(y,x)]
#   dfh[,z1:=z/rt]
#   dfh[,z2:=z/r]
#   mm     <-  1
#   for (ii in 0:Niter) {
#     mm <- mm*(-1)
#     dfh[,a1:=a0+mm*(rt+0.000005*rt^2)/1000*(ii/2)/180*pi]
#     dfh[,sina1:=sin(a1)]
#     dfh[,cosa1:=cos(a1)]
#     dfs=scale(dfh[,.(sina1,cosa1,z1,z2)])
# 	cx <- c(w1,w1,w2,w3)
#     for (jj in 1:ncol(dfs)) dfs[,jj] <- dfs[,jj]*cx[jj]
#     res=dbscan(dfs,eps=0.0035,minPts = 1)
#     dfh[,s2:=res$cluster]
#     dfh[,N2:=.N, by=s2]
#     maxs1 <- max(dfh$s1)
#     dfh[,s1:=ifelse(N2>N1 & N2<20,s2+maxs1,s1)]
#     dfh[,s1:=as.integer(as.factor(s1))]
#     dfh[,N1:=.N, by=s1]    
#   }
#   return(dfh$s1)
# }

In [11]:
def Fun4BO(w1,w2,w3,Niter):
    track_id = trackML(hits, w1,w2,w3,Niter)
    
    sum_score=0
    sum = 0
    submission = pd.DataFrame(columns=['event_id', 'hit_id', 'track_id'],
        data=np.column_stack(([int(event_id),]*len(hits), hits.hit_id.values, track_id))
    ).astype(int)
    for i in range(8):
        submission = extend(submission,hits)
        score = score_event(truth, submission)
        print('[%2d] score : %0.8f'%(i, score))
        sum_score += score
        sum += 1

    print('--------------------------------------')
    sc = sum_score/sum
    print(sc)
    
    return sc

In [12]:
def Fun4BO2(w6, w7):
    
    w1 = 1.1932215111905984
    w2 = 0.39740553885387364
    w3 = 0.3512647720585538
    w4 = 0.1470
    w5 = 0.2691
#     w6 = 0.0020
    Niter=179
    print(w7)
    track_id = trackML3(hits, w1,w2,w3,w4,w5,w6,w7,Niter)
    
    sum_score=0
    sum = 0
    submission = pd.DataFrame(columns=['event_id', 'hit_id', 'track_id'],
        data=np.column_stack(([int(event_id),]*len(hits), hits.hit_id.values, track_id))
    ).astype(int)
    for i in range(8):
        submission = extend(submission,hits)
        score = score_event(truth, submission)
        print('[%2d] score : %0.8f'%(i, score))
        sum_score += score
        sum += 1

    print('--------------------------------------')
    sc = sum_score/sum
    print(sc)
    
    return sc

In [13]:
def Fun4BO21(w12):
    
#     w1 = 1.1932215111905984
#     w2 = 0.39740553885387364
#     w3 = 0.3512647720585538
#     w4 = 0.1470
#     w5 = 0.01201
#     w6 = 0.0205
#     w7 = 0.0026
    w1 = 1.1932215111905984
    w2 = 0.39740553885387364
    w3 = 0.3512647720585538
    w4 = 0.1470
    w5 = 0.01201
    w6 = 0.0003864
    w7 = 0.0205
    w8 = 0.0049
    w9 = 0.00121
    w10 = 1.4930496676654575e-05
    w11 = 0.0318
    Niter=179
    Niter=247
    print(w12)
    track_id = trackML31(hits, w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12, Niter)
    
    sum_score=0
    sum = 0
    submission = pd.DataFrame(columns=['event_id', 'hit_id', 'track_id'],
        data=np.column_stack(([int(event_id),]*len(hits), hits.hit_id.values, track_id))
    ).astype(int)
    for i in range(8):
        submission = extend(submission,hits)
        score = score_event(truth, submission)
        print('[%2d] score : %0.8f'%(i, score))
        sum_score += score
        sum += 1

    print('--------------------------------------')
    sc = sum_score/sum
    print(sc)
    
    return sc

In [14]:
#######################################
# function for Bayessian Optimization #
#   (needs lists: Score and Pred)     #
#######################################
# Fun4BO <- function(w1,w2,w3,Niter) { 
#    dfh$s1 <- trackML(dfh,w1,w2,w3,Niter)
#    sub=data.table(event_id=nev,hit_id=dfh$hit_id,track_id=dfh$s1)
#    sc <- score(sub,dft)
#    list(Score=sc,Pred=0)
# }

In [17]:
# def run_dbscan():

data_dir = '../data/train'

#     event_ids = [
#             '000001030',##
#             '000001025','000001026','000001027','000001028','000001029',
#     ]

event_ids = [
        '000001030',##

]

sum=0
sum_score=0
for i,event_id in enumerate(event_ids):
    particles = pd.read_csv(data_dir + '/event%s-particles.csv'%event_id)
    hits  = pd.read_csv(data_dir + '/event%s-hits.csv'%event_id)
    cells = pd.read_csv(data_dir + '/event%s-cells.csv'%event_id)
    truth = pd.read_csv(data_dir + '/event%s-truth.csv'%event_id)
    particles = pd.read_csv(data_dir + '/event%s-particles.csv'%event_id)
    
    truth = pd.merge(truth, particles, how='left', on='particle_id')
    hits = pd.merge(hits, truth, how='left', on='hit_id')
    
    w1 = [0.9, 1.2]
    w2 = [0.3, 0.7]
    w3 = [0.1, 0.4]
    Niter = [140, 190]
    
    
#     bo = BayesianOptimization(Fun4BO,pbounds = {'w1':w1,'w2':w2,'w3':w3,'Niter':Niter})
#     bo.maximize(init_points = 3, n_iter = 20, acq = "ucb", kappa = 2.576)
    w1 = 1.1932215111905984
    w2 = 0.39740553885387364
    w3 = 0.3512647720585538
    w4 = 0.1470
    w5 = 0.2691
    w6 = 0.0020
    w6 = [0.0000001, 1.2] 
    w10 = [0.00001, 1.2] 
    w12 = [0.00001, 0.1] 
    Niter = 179
    w12 = 0.00045
#     Fun4BO21(w12)
#     for w12 in np.arange(0.0002, 0.003, 0.00005):
#         print(w12)
#         Fun4BO21(w12)
#     bo = BayesianOptimization(Fun4BO21,pbounds = {'w12':w12})
#     bo.maximize(init_points = 20, n_iter = 5, acq = "ucb", kappa = 2.576)

# z1+z2: 13 | 05m39s |    0.55616 |    0.1124 | 
# z1 * z2: 13 | 05m40s |    0.55637 |    0.0404 | 
# tt = cos(theta), theta = np.arctan2(rt,z): 4 | 06m01s |    0.55196 |    0.2711 | 
# tt, theta = np.arctan2(rt2,z2);  8 | 05m39s |    0.55604 |    0.0005 | 
# cos + sin: 15 | 05m39s |    0.55714 |    0.2691 | 
# cos-sin: 9 | 05m51s |    0.55714 |    0.0020 | 
# cos+sin/cos-sin: 8 | 06m03s |    0.55694 |    0.0012 | 
# ctt, stt, ctt+stt/ctt-stt: 8 | 06m03s |    0.55273 |    0.0000 | 
# ctt: 10 | 05m39s |    0.55613 |    0.0047 | 
# caa * stt: 7 | 05m38s |    0.55613 |    0.0022 |
# saa * ctt: 15 | 05m38s |    0.55613 |    0.0033 |
# c1 = caa*stt, c2 = saa*ctt, c1+c2: 10 | 05m43s |    0.55622 |    0.0571 | 
# caa * saa: 7 | 05m45s |    0.55639 |    0.1548 | 
# caa/saa: 13 | 05m43s |    0.55613 |    0.000001 | 
# xx1, xx2: 12 | 06m04s |    0.55613 |    0.000001 |    0.000001 | 

# hdbscan - braycurtis: 0.14424123982821765
# hdbscan - euclidean : 0.1311

# eps: 0.0040: 0.57549
# tt: 21 | 07m08s |    0.57208 |    0.0000 |  (1e-07)
# ctt, stt (after new eqn: 25 | 07m33s |    0.57254 |    0.0026 | 
# ctt, stt: 0.00261: 0.5727074941034839
# caa, saa, z1, z2, rt/r, x/r, z3, ctt, stt, y1, y3:
# w1 = 1.1932215111905984, w2 = 0.39740553885387364, w3 = 0.3512647720585538, w4 = 0.1470, w5 = 0.01201
# w6 = 0.0205, w7 = 0.00261, w8 = 0.0049, w9 = 0.0012 (0.5717942069958433)
# 
# X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2, rt/r, x/r, y/r, z3, y1, y3])):
# w1 = 1.1932215111905984 w2 = 0.39740553885387364 w3 = 0.3512647720585538 w4 = 0.1470 w5 = 0.01201 w6 = 0.0003864 
# w7 = 0.0205 w8 = 0.0049 w9 = 0.00121 (0.57343)
# ctt, stt: 13 | 08m16s |    0.57343 |    0.0003 | (0.00032967312140735677)
# ctt, stt: 21 | 08m20s |    0.57343 |    0.0000 |  (1.4930496676654575e-05)
# ctt, stt: 15 | 08m14s |    0.57351 |    0.8435 | (t1 = theta+mm*(rt+ w11*rt**2)/1000*(ii/2)/180*np.pi)
# z4: 0.0245 (0.5735925042985041)
# # z4 0.0318 (0.5736635664313068)
# x4: 0.00001 (0.5735421714482896)
# x4: 0.00025 (0.5736999491677117)
# x4: 0.00045 (0.5737240529228144)

In [18]:
def trackML32(w15):
    w1 = 1.1932215111905984
    w2 = 0.39740553885387364
    w3 = 0.3512647720585538
    w4 = 0.1470
    w5 = 0.01201
    w6 = 0.0003864
    w7 = 0.0205
    w8 = 0.0049
    w9 = 0.00121
    w10 = 1.4930496676654575e-05
    w11 = 0.0318
    w12 = 0.00045
    w13 = 0.0055
    w14 = 0.3
    Niter=179
    Niter=246

    df = hits
    x  = df.x.values
    y  = df.y.values
    z  = df.z.values

    dz = 0
    z = z + dz

    rt  = np.sqrt(x**2+y**2)
    r  = np.sqrt(x**2+y**2+z**2)
    a0  = np.arctan2(y,x)

    x2 = x/r
    y2 = y/r


    phi = np.arctan2(y, x)
    phi_deg= np.degrees(np.arctan2(y, x))


    z1 = z/rt
    z2 = z/r

    z3 = np.log1p(abs(z/r))*np.sign(z)

    x1 = x/rt
    y1 = y/rt

    y3 = np.log1p(abs(y/r))*np.sign(y)

    theta = np.arctan2(rt, z)
    theta_deg = np.degrees(np.arctan2(rt, z))
    tt = np.tan(theta_deg)

    z4 = np.sqrt(abs(z/rt))

    x4 = np.sqrt(abs(x/r))
    y4 = np.sqrt(abs(y/r))

    mm = 1
    ls = []

    #     print(Niter)
    #     Niter = Niter.astype(np.int32)
    #     print(Niter)
    #     print(w1, w2, w3, Niter)

    for ii in range(Niter):
        mm = mm * (-1)

        a1 = a0+mm*(rt+ 0.0000145*rt**2)/1000*(ii/2)/180*np.pi
    #         print(a0, a1)
        saa = np.sin(a1)
        caa = np.cos(a1)

        t1 = theta+mm*(rt+ 0.8435*rt**2)/1000*(ii/2)/180*np.pi
        ctt = np.cos(t1)
        stt = np.sin(t1)
        ttt = np.tan(t1)
        deps = 0.0000025
    #         X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2, rt/r, x/r, z3, ctt, stt]))
        X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2, rt/r, x/r, y/r, z3, y1, y3, 
                                                            ctt, stt, z4, x4]))
    #         print(X.shape)

    #         cx = [w1,w1,w2,w3, w4, w5, w6, w7, w7]
        cx = [w1,w1,w2,w3, w4, w5, w6, w7, w8, w9, w10, w10, w11, w12]
        for jj in range(X.shape[1]): 
             X[:,jj] = X[:,jj]*cx[jj]
        deps = 0.0000025
    #         cl = hdbscan.HDBSCAN(min_samples=1,min_cluster_size=7,cluster_selection_method='leaf',metric='euclidean', leaf_size=50)
    #         l = cl.fit_predict(X)+1

        l= DBSCAN(eps=0.0035,min_samples=1,metric='euclidean',n_jobs=8).fit(X).labels_
    #         l= DBSCAN(eps=w7,min_samples=1,metric='euclidean',n_jobs=8).fit(X).labels_
        ls.append(l)

    for ii in range(Niter):
        mm = mm * (1)

        a1 = a0+mm*(rt+0.000005*rt**2)/1000*(ii/2)/180*np.pi
    #         print(a0, a1)
        saa = np.sin(a1)
        caa = np.cos(a1)

        t1 = theta+mm*(rt+ 0.8435*rt**2)/1000*(ii/2)/180*np.pi
        ctt = np.cos(t1)
        stt = np.sin(t1)
        ttt = np.tan(t1)
        deps = 0.0000025
    #         X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2, rt/r, x/r, z3, ctt, stt]))
        X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2, rt/r, x/r, y/r, z3, y1, y3, 
                                                            ctt, stt, z4, x4]))
        
        X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2]))
    #         print(X.shape)

    #         cx = [w1,w1,w2,w3, w4, w5, w6, w7, w7]
        cx = [w1,w1,w2,w3, w4, w5, w6, w7, w8, w9, w10, w10, w11, w12]
        cx = [w13,w13,w14,w15]
        for jj in range(X.shape[1]): 
             X[:,jj] = X[:,jj]*cx[jj]
        deps = 0.0000025
    #         cl = hdbscan.HDBSCAN(min_samples=1,min_cluster_size=7,cluster_selection_method='leaf',metric='euclidean', leaf_size=50)
    #         l = cl.fit_predict(X)+1

        l= DBSCAN(eps=0.0035,min_samples=1,metric='euclidean',n_jobs=8).fit(X).labels_
    #         l= DBSCAN(eps=w7,min_samples=1,metric='euclidean',n_jobs=8).fit(X).labels_
        ls.append(l)

    num_hits=len(df)
    labels = np.zeros(num_hits,np.int32)
    counts = np.zeros(num_hits,np.int32)
    for l in ls:
        c = make_counts(l)
        idx = np.where((c-counts>0) & (c<20))[0]
        labels[idx] = l[idx] + labels.max()
        counts = make_counts(labels)

    track_id = labels
    sum_score=0
    sum = 0
    submission = pd.DataFrame(columns=['event_id', 'hit_id', 'track_id'],
        data=np.column_stack(([int(event_id),]*len(hits), hits.hit_id.values, track_id))
    ).astype(int)
    for i in range(8):
        submission = extend(submission,hits)
        score = score_event(truth, submission)
        print('[%2d] score : %0.8f'%(i, score))
        sum_score += score
        sum += 1

    print('--------------------------------------')
    sc = sum_score/sum
    print(sc)

In [23]:
for w15 in np.arange(0.001, 0.6, 0.0005):
    print(w15)
    trackML32(w15)
# w13: 0.0055: 0.5739099833436064
# w14: test z1 for dual iter (0.3): 0.5741929067448117

0.001
 179.0000000[ 0] score : 0.56418913
 179.0000000[ 1] score : 0.57229419
 179.0000000[ 2] score : 0.57475772
 179.0000000[ 3] score : 0.57474359
 179.0000000[ 4] score : 0.57614395
 179.0000000[ 5] score : 0.57557319
 179.0000000[ 6] score : 0.57634783
 179.0000000[ 7] score : 0.57574281
--------------------------------------
0.5737240529228144
0.0015
 179.0000000[ 0] score : 0.56418913
 179.0000000[ 1] score : 0.57229419
 179.0000000[ 2] score : 0.57475772
 179.0000000[ 3] score : 0.57474359
 179.0000000[ 4] score : 0.57614395
 179.0000000[ 5] score : 0.57557319
 179.0000000[ 6] score : 0.57634783
 179.0000000[ 7] score : 0.57574281
--------------------------------------
0.5737240529228144
0.002
 179.0000000[ 0] score : 0.56418913
 179.0000000[ 1] score : 0.57229419
 179.0000000[ 2] score : 0.57475772
 179.0000000[ 3] score : 0.57474359
 179.0000000[ 4] score : 0.57614395
 179.0000000[ 5] score : 0.57557319
 179.0000000[ 6] score : 0.57634783
 179.0000000[ 7] score : 0.57574281
-

 179.0000000[ 0] score : 0.56421750
 179.0000000[ 1] score : 0.57232257
 179.0000000[ 2] score : 0.57478610
 179.0000000[ 3] score : 0.57477197
 179.0000000[ 4] score : 0.57617233
 179.0000000[ 5] score : 0.57560157
 179.0000000[ 6] score : 0.57637621
 179.0000000[ 7] score : 0.57577119
--------------------------------------
0.5737524279629354
0.013000000000000001
 179.0000000[ 0] score : 0.56421750
 179.0000000[ 1] score : 0.57232257
 179.0000000[ 2] score : 0.57478610
 179.0000000[ 3] score : 0.57477197
 179.0000000[ 4] score : 0.57617233
 179.0000000[ 5] score : 0.57560157
 179.0000000[ 6] score : 0.57637621
 179.0000000[ 7] score : 0.57577119
--------------------------------------
0.5737524279629354
0.013500000000000002
 179.0000000[ 0] score : 0.56421750
 179.0000000[ 1] score : 0.57232257
 179.0000000[ 2] score : 0.57478610
 179.0000000[ 3] score : 0.57477197
 179.0000000[ 4] score : 0.57617233
 179.0000000[ 5] score : 0.57560157
 179.0000000[ 6] score : 0.57637621
 179.0000000[ 

 179.0000000[ 0] score : 0.56425426
 179.0000000[ 1] score : 0.57235932
 179.0000000[ 2] score : 0.57482286
 179.0000000[ 3] score : 0.57480872
 179.0000000[ 4] score : 0.57620908
 179.0000000[ 5] score : 0.57563832
 179.0000000[ 6] score : 0.57641296
 179.0000000[ 7] score : 0.57580794
--------------------------------------
0.5737891846130918
0.0245
 179.0000000[ 0] score : 0.56425426
 179.0000000[ 1] score : 0.57235932
 179.0000000[ 2] score : 0.57482286
 179.0000000[ 3] score : 0.57480872
 179.0000000[ 4] score : 0.57620908
 179.0000000[ 5] score : 0.57563832
 179.0000000[ 6] score : 0.57641296
 179.0000000[ 7] score : 0.57580794
--------------------------------------
0.5737891846130918
0.025
 179.0000000[ 0] score : 0.56425426
 179.0000000[ 1] score : 0.57235932
 179.0000000[ 2] score : 0.57482286
 179.0000000[ 3] score : 0.57480872
 179.0000000[ 4] score : 0.57620908
 179.0000000[ 5] score : 0.57563832
 179.0000000[ 6] score : 0.57641296
 179.0000000[ 7] score : 0.57580794
-------

 179.0000000[ 0] score : 0.56420935
 179.0000000[ 1] score : 0.57231441
 179.0000000[ 2] score : 0.57477794
 179.0000000[ 3] score : 0.57476381
 179.0000000[ 4] score : 0.57616417
 179.0000000[ 5] score : 0.57559341
 179.0000000[ 6] score : 0.57636805
 179.0000000[ 7] score : 0.57576303
--------------------------------------
0.5737442713929006
0.036000000000000004
 179.0000000[ 0] score : 0.56420935
 179.0000000[ 1] score : 0.57231441
 179.0000000[ 2] score : 0.57477794
 179.0000000[ 3] score : 0.57476381
 179.0000000[ 4] score : 0.57616417
 179.0000000[ 5] score : 0.57559341
 179.0000000[ 6] score : 0.57636805
 179.0000000[ 7] score : 0.57576303
--------------------------------------
0.5737442713929006
0.036500000000000005
 179.0000000[ 0] score : 0.56420935
 179.0000000[ 1] score : 0.57231441
 179.0000000[ 2] score : 0.57477794
 179.0000000[ 3] score : 0.57476381
 179.0000000[ 4] score : 0.57616417
 179.0000000[ 5] score : 0.57559341
 179.0000000[ 6] score : 0.57636805
 179.0000000[ 

 179.0000000[ 0] score : 0.56429763
 179.0000000[ 1] score : 0.57240269
 179.0000000[ 2] score : 0.57486622
 179.0000000[ 3] score : 0.57485209
 179.0000000[ 4] score : 0.57625245
 179.0000000[ 5] score : 0.57568169
 179.0000000[ 6] score : 0.57645633
 179.0000000[ 7] score : 0.57585131
--------------------------------------
0.5738325491832765
0.0475
 179.0000000[ 0] score : 0.56429763
 179.0000000[ 1] score : 0.57240269
 179.0000000[ 2] score : 0.57486622
 179.0000000[ 3] score : 0.57485209
 179.0000000[ 4] score : 0.57625245
 179.0000000[ 5] score : 0.57568169
 179.0000000[ 6] score : 0.57645633
 179.0000000[ 7] score : 0.57585131
--------------------------------------
0.5738325491832765
0.048
 179.0000000[ 0] score : 0.56429763
 179.0000000[ 1] score : 0.57240269
 179.0000000[ 2] score : 0.57486622
 179.0000000[ 3] score : 0.57485209
 179.0000000[ 4] score : 0.57625245
 179.0000000[ 5] score : 0.57568169
 179.0000000[ 6] score : 0.57645633
 179.0000000[ 7] score : 0.57585131
-------

KeyboardInterrupt: 

In [36]:
for l in ls:
    x,reverse,count = np.unique(l,return_counts=True,return_inverse=True)
    print(x, count)

[    0     1     2 ... 86393 86394 86395] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86453 86454 86455] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86285 86286 86287] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86365 86366 86367] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86224 86225 86226] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86378 86379 86380] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86296 86297 86298] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86250 86251 86252] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86294 86295 86296] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86046 86047 86048] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86100 86101 86102] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86062 86063 86064] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86261 86262 86263] [2 1 2 ... 1 1 1]
[    0     1     2 ... 85864 85865 85866] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86092 86093 86094] [2 1 2 ... 1 1 1]
[    0     1     2 ... 85711 85712 85713] [2 1 2 ... 1 1 1]
[    0     1     2 ... 86057 86058 86059

[    0     1     2 ... 92264 92265 92266] [ 2 13  2 ...  1  1  1]
[    0     1     2 ... 92940 92941 92942] [ 2  1 16 ...  1  1  1]
[    0     1     2 ... 92282 92283 92284] [ 2 13  2 ...  1  1  1]
[    0     1     2 ... 92955 92956 92957] [ 2  1 16 ...  1  1  1]
[    0     1     2 ... 92358 92359 92360] [ 2 13  2 ...  1  1  1]
[    0     1     2 ... 93000 93001 93002] [ 2  1 16 ...  1  1  1]
[    0     1     2 ... 92554 92555 92556] [ 2 13  2 ...  1  1  1]
[    0     1     2 ... 93149 93150 93151] [ 2  1 16 ...  1  1  1]
[    0     1     2 ... 92625 92626 92627] [ 2 13  2 ...  1  1  1]
[    0     1     2 ... 93156 93157 93158] [ 2  1 16 ...  1  1  1]
[    0     1     2 ... 92768 92769 92770] [ 2 13  2 ...  1  1  1]
[    0     1     2 ... 93321 93322 93323] [ 2  1 16 ...  1  1  1]
[    0     1     2 ... 92911 92912 92913] [ 2 13  2 ...  1  1  1]
[    0     1     2 ... 93508 93509 93510] [2 1 2 ... 1 1 1]
[    0     1     2 ... 92983 92984 92985] [ 2 13  2 ...  1  1  1]
[    0     1    

In [17]:
# def run_dbscan():

data_dir = '../data/train'

#     event_ids = [
#             '000001030',##
#             '000001025','000001026','000001027','000001028','000001029',
#     ]

event_ids = [
        '000001030',##

]

sum=0
sum_score=0
for i,event_id in enumerate(event_ids):
    particles = pd.read_csv(data_dir + '/event%s-particles.csv'%event_id)
    hits  = pd.read_csv(data_dir + '/event%s-hits.csv'%event_id)
    cells = pd.read_csv(data_dir + '/event%s-cells.csv'%event_id)
    truth = pd.read_csv(data_dir + '/event%s-truth.csv'%event_id)
    particles = pd.read_csv(data_dir + '/event%s-particles.csv'%event_id)
    
    truth = pd.merge(truth, particles, how='left', on='particle_id')
    hits = pd.merge(hits, truth, how='left', on='hit_id')
    
    w1 = [0.9, 1.2]
    w2 = [0.3, 0.7]
    w3 = [0.1, 0.4]
    Niter = [140, 190]
    
    
#     bo = BayesianOptimization(Fun4BO,pbounds = {'w1':w1,'w2':w2,'w3':w3,'Niter':Niter})
#     bo.maximize(init_points = 3, n_iter = 20, acq = "ucb", kappa = 2.576)
    w1 = 1.1932215111905984
    w2 = 0.39740553885387364
    w3 = 0.3512647720585538
    w4 = 0.1470
    w5 = 0.2691
    w6 = 0.0020
    w6 = [0.0000001, 1.2] 
    w10 = [0.00001, 1.2] 
    w12 = [0.00001, 0.1] 
    Niter = 179
    w12 = 0.00045
#     Fun4BO21(w12)
#     for w12 in np.arange(0.0002, 0.003, 0.00005):
#         print(w12)
#         Fun4BO21(w12)
#     bo = BayesianOptimization(Fun4BO21,pbounds = {'w12':w12})
#     bo.maximize(init_points = 20, n_iter = 5, acq = "ucb", kappa = 2.576)

# z1+z2: 13 | 05m39s |    0.55616 |    0.1124 | 
# z1 * z2: 13 | 05m40s |    0.55637 |    0.0404 | 
# tt = cos(theta), theta = np.arctan2(rt,z): 4 | 06m01s |    0.55196 |    0.2711 | 
# tt, theta = np.arctan2(rt2,z2);  8 | 05m39s |    0.55604 |    0.0005 | 
# cos + sin: 15 | 05m39s |    0.55714 |    0.2691 | 
# cos-sin: 9 | 05m51s |    0.55714 |    0.0020 | 
# cos+sin/cos-sin: 8 | 06m03s |    0.55694 |    0.0012 | 
# ctt, stt, ctt+stt/ctt-stt: 8 | 06m03s |    0.55273 |    0.0000 | 
# ctt: 10 | 05m39s |    0.55613 |    0.0047 | 
# caa * stt: 7 | 05m38s |    0.55613 |    0.0022 |
# saa * ctt: 15 | 05m38s |    0.55613 |    0.0033 |
# c1 = caa*stt, c2 = saa*ctt, c1+c2: 10 | 05m43s |    0.55622 |    0.0571 | 
# caa * saa: 7 | 05m45s |    0.55639 |    0.1548 | 
# caa/saa: 13 | 05m43s |    0.55613 |    0.000001 | 
# xx1, xx2: 12 | 06m04s |    0.55613 |    0.000001 |    0.000001 | 

# hdbscan - braycurtis: 0.14424123982821765
# hdbscan - euclidean : 0.1311

# eps: 0.0040: 0.57549
# tt: 21 | 07m08s |    0.57208 |    0.0000 |  (1e-07)
# ctt, stt (after new eqn: 25 | 07m33s |    0.57254 |    0.0026 | 
# ctt, stt: 0.00261: 0.5727074941034839
# caa, saa, z1, z2, rt/r, x/r, z3, ctt, stt, y1, y3:
# w1 = 1.1932215111905984, w2 = 0.39740553885387364, w3 = 0.3512647720585538, w4 = 0.1470, w5 = 0.01201
# w6 = 0.0205, w7 = 0.00261, w8 = 0.0049, w9 = 0.0012 (0.5717942069958433)
# 
# X = StandardScaler().fit_transform(np.column_stack([caa, saa, z1, z2, rt/r, x/r, y/r, z3, y1, y3])):
# w1 = 1.1932215111905984 w2 = 0.39740553885387364 w3 = 0.3512647720585538 w4 = 0.1470 w5 = 0.01201 w6 = 0.0003864 
# w7 = 0.0205 w8 = 0.0049 w9 = 0.00121 (0.57343)
# ctt, stt: 13 | 08m16s |    0.57343 |    0.0003 | (0.00032967312140735677)
# ctt, stt: 21 | 08m20s |    0.57343 |    0.0000 |  (1.4930496676654575e-05)
# ctt, stt: 15 | 08m14s |    0.57351 |    0.8435 | (t1 = theta+mm*(rt+ w11*rt**2)/1000*(ii/2)/180*np.pi)
# z4: 0.0245 (0.5735925042985041)
# # z4 0.0318 (0.5736635664313068)
# x4: 0.00001 (0.5735421714482896)
# x4: 0.00025 (0.5736999491677117)
# x4: 0.00045 (0.5737240529228144)

In [151]:
# def run_dbscan():

data_dir = '../data/train'

#     event_ids = [
#             '000001030',##
#             '000001025','000001026','000001027','000001028','000001029',
#     ]

event_ids = [
        '000001030',##

]

sum=0
sum_score=0
for i,event_id in enumerate(event_ids):
    particles = pd.read_csv(data_dir + '/event%s-particles.csv'%event_id)
    hits  = pd.read_csv(data_dir + '/event%s-hits.csv'%event_id)
    cells = pd.read_csv(data_dir + '/event%s-cells.csv'%event_id)
    truth = pd.read_csv(data_dir + '/event%s-truth.csv'%event_id)
    particles = pd.read_csv(data_dir + '/event%s-particles.csv'%event_id)
    
    truth = pd.merge(truth, particles, how='left', on='particle_id')
    hits = pd.merge(hits, truth, how='left', on='hit_id')
    
    w1 = [0.9, 1.2]
    w2 = [0.3, 0.7]
    w3 = [0.1, 0.4]
    Niter = [140, 190]
    
    
#     bo = BayesianOptimization(Fun4BO,pbounds = {'w1':w1,'w2':w2,'w3':w3,'Niter':Niter})
#     bo.maximize(init_points = 3, n_iter = 20, acq = "ucb", kappa = 2.576)
    w1 = 1.1932215111905984
    w2 = 0.39740553885387364
    w3 = 0.3512647720585538
    w4 = 0.1470
    w5 = 0.2691
    w6 = 0.0020
    w6 = [0.0000001, 1.2] 
    w7 = [0.0000001, 1.2] 
    Niter = 179
    
    bo = BayesianOptimization(Fun4BO2,pbounds = {'w6':w6,'w7':w7})
    bo.maximize(init_points = 5, n_iter = 10, acq = "ucb", kappa = 2.576)

# z1+z2: 13 | 05m39s |    0.55616 |    0.1124 | 
# z1 * z2: 13 | 05m40s |    0.55637 |    0.0404 | 
# tt = cos(theta), theta = np.arctan2(rt,z): 4 | 06m01s |    0.55196 |    0.2711 | 
# tt, theta = np.arctan2(rt2,z2);  8 | 05m39s |    0.55604 |    0.0005 | 
# cos + sin: 15 | 05m39s |    0.55714 |    0.2691 | 
# cos-sin: 9 | 05m51s |    0.55714 |    0.0020 | 
# cos+sin/cos-sin: 8 | 06m03s |    0.55694 |    0.0012 | 
# ctt, stt, ctt+stt/ctt-stt: 8 | 06m03s |    0.55273 |    0.0000 | 
# ctt: 10 | 05m39s |    0.55613 |    0.0047 | 
# caa * stt: 7 | 05m38s |    0.55613 |    0.0022 |
# saa * ctt: 15 | 05m38s |    0.55613 |    0.0033 |
# c1 = caa*stt, c2 = saa*ctt, c1+c2: 10 | 05m43s |    0.55622 |    0.0571 | 
# caa * saa: 7 | 05m45s |    0.55639 |    0.1548 | 
# caa/saa: 13 | 05m43s |    0.55613 |    0.000001 | 
# xx1, xx2: 12 | 06m04s |    0.55613 |    0.000001 |    0.000001 | 

Initialization
-----------------------------------------------------
 Step |   Time |      Value |        w6 |        w7 | 
0.6438083918550258
 179.0000000[ 0] score : 0.53909026
 179.0000000[ 1] score : 0.54453204
 179.0000000[ 2] score : 0.54584807
 179.0000000[ 3] score : 0.54665394
 179.0000000[ 4] score : 0.54637718
 179.0000000[ 5] score : 0.54672196
 179.0000000[ 6] score : 0.54612357
 179.0000000[ 7] score : 0.54643417
--------------------------------------
0.5452226494326484
    1 | 06m35s |    0.54522 |    0.4154 |    0.6438 | 
0.13010260123925543
 179.0000000[ 0] score : 0.53765585
 179.0000000[ 1] score : 0.54275636
 179.0000000[ 2] score : 0.54399014
 179.0000000[ 3] score : 0.54453231
 179.0000000[ 4] score : 0.54494417
 179.0000000[ 5] score : 0.54511491
 179.0000000[ 6] score : 0.54470390
 179.0000000[ 7] score : 0.54500309
--------------------------------------
0.5435875913581831
    2 | 06m18s |    0.54359 |    1.1177 |    0.1301 | 
0.2673415946824791
 179.0000000[ 0]

/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:335: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "


Bayesian Optimization
-----------------------------------------------------
 Step |   Time |      Value |        w6 |        w7 | 
1e-07
 179.0000000[ 0] score : 0.54945841
 179.0000000[ 1] score : 0.55564882
 179.0000000[ 2] score : 0.55701564
 179.0000000[ 3] score : 0.55734112
 179.0000000[ 4] score : 0.55756978
 179.0000000[ 5] score : 0.55762537
 179.0000000[ 6] score : 0.55712773
 179.0000000[ 7] score : 0.55722315
--------------------------------------
0.5561262528478478
    6 | 05m53s |    0.55613 |    0.0000 |    0.0000 | 


/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:335: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "


1.1997780528661428
 179.0000000[ 0] score : 0.54137124
 179.0000000[ 1] score : 0.54751761
 179.0000000[ 2] score : 0.54908984
 179.0000000[ 3] score : 0.54927465
 179.0000000[ 4] score : 0.54945186
 179.0000000[ 5] score : 0.54951666
 179.0000000[ 6] score : 0.54928405
 179.0000000[ 7] score : 0.54931714
--------------------------------------
0.5481028806786682
    7 | 06m16s |    0.54810 |    0.0033 |    1.1998 | 


/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:457: UserWarning: fmin_l_bfgs_b terminated abnormally with the  state: {'grad': array([-1.22049496e-05]), 'task': b'ABNORMAL_TERMINATION_IN_LNSRCH', 'funcalls': 51, 'nit': 5, 'warnflag': 2}
  " state: %s" % convergence_dict)
/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:335: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "


0.00773612307984523
 179.0000000[ 0] score : 0.53829291
 179.0000000[ 1] score : 0.54375212
 179.0000000[ 2] score : 0.54455031
 179.0000000[ 3] score : 0.54517109
 179.0000000[ 4] score : 0.54546027
 179.0000000[ 5] score : 0.54567542
 179.0000000[ 6] score : 0.54526374
 179.0000000[ 7] score : 0.54560177
--------------------------------------
0.5442209543796312
    8 | 06m32s |    0.54422 |    0.9733 |    0.0077 | Warning: Test point chose at random due to repeated sample.



/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:457: UserWarning: fmin_l_bfgs_b terminated abnormally with the  state: {'grad': array([-0.00013319]), 'task': b'ABNORMAL_TERMINATION_IN_LNSRCH', 'funcalls': 53, 'nit': 7, 'warnflag': 2}
  " state: %s" % convergence_dict)
/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:335: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "


0.006227350121840072
 179.0000000[ 0] score : 0.54856448
 179.0000000[ 1] score : 0.55495181
 179.0000000[ 2] score : 0.55616072
 179.0000000[ 3] score : 0.55645280
 179.0000000[ 4] score : 0.55673325
 179.0000000[ 5] score : 0.55678883
 179.0000000[ 6] score : 0.55629119
 179.0000000[ 7] score : 0.55638661
--------------------------------------
0.5552912122180405
    9 | 05m57s |    0.55529 |    0.0036 |    0.0062 | 


/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:335: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "


1.1999999742482206
 179.0000000[ 0] score : 0.53600803
 179.0000000[ 1] score : 0.54202660
 179.0000000[ 2] score : 0.54327701
 179.0000000[ 3] score : 0.54448418
 179.0000000[ 4] score : 0.54401889
 179.0000000[ 5] score : 0.54410522
 179.0000000[ 6] score : 0.54367383
 179.0000000[ 7] score : 0.54411096
--------------------------------------
0.5427130911619577
   10 | 06m36s |    0.54271 |    1.2000 |    1.2000 | 


/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:457: UserWarning: fmin_l_bfgs_b terminated abnormally with the  state: {'grad': array([-0.00038894]), 'task': b'ABNORMAL_TERMINATION_IN_LNSRCH', 'funcalls': 48, 'nit': 4, 'warnflag': 2}
  " state: %s" % convergence_dict)
/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:457: UserWarning: fmin_l_bfgs_b terminated abnormally with the  state: {'grad': array([-0.00018047]), 'task': b'ABNORMAL_TERMINATION_IN_LNSRCH', 'funcalls': 53, 'nit': 5, 'warnflag': 2}
  " state: %s" % convergence_dict)
/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:335: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "


0.8364256197873428
 179.0000000[ 0] score : 0.54160642
 179.0000000[ 1] score : 0.54827308
 179.0000000[ 2] score : 0.54894094
 179.0000000[ 3] score : 0.54936737
 179.0000000[ 4] score : 0.54971602
 179.0000000[ 5] score : 0.54987162
 179.0000000[ 6] score : 0.54935095
 179.0000000[ 7] score : 0.54973077
--------------------------------------
0.5483571473522514
   11 | 06m21s |    0.54836 |    0.0000 |    0.8364 | 


/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:457: UserWarning: fmin_l_bfgs_b terminated abnormally with the  state: {'grad': array([0.00179457]), 'task': b'ABNORMAL_TERMINATION_IN_LNSRCH', 'funcalls': 53, 'nit': 5, 'warnflag': 2}
  " state: %s" % convergence_dict)
/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:457: UserWarning: fmin_l_bfgs_b terminated abnormally with the  state: {'grad': array([-0.00054921]), 'task': b'ABNORMAL_TERMINATION_IN_LNSRCH', 'funcalls': 54, 'nit': 4, 'warnflag': 2}
  " state: %s" % convergence_dict)
/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:457: UserWarning: fmin_l_bfgs_b terminated abnormally with the  state: {'grad': array([-0.00017087]), 'task': b'ABNORMAL_TERMINATION_IN_LNSRCH', 'funcalls': 65, 'nit': 7, 'warnflag': 2}
  " state: %s" % convergence_dict)
/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sk

1.1997925580015492
 179.0000000[ 0] score : 0.53691911
 179.0000000[ 1] score : 0.54245156
 179.0000000[ 2] score : 0.54405084
 179.0000000[ 3] score : 0.54472488
 179.0000000[ 4] score : 0.54450674
 179.0000000[ 5] score : 0.54480138
 179.0000000[ 6] score : 0.54451682
 179.0000000[ 7] score : 0.54464852
--------------------------------------
0.543327479207075
   12 | 06m16s |    0.54333 |    0.6144 |    1.1998 | 


/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:335: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "


0.6241812937500543
 179.0000000[ 0] score : 0.53665998
 179.0000000[ 1] score : 0.54215378
 179.0000000[ 2] score : 0.54321330
 179.0000000[ 3] score : 0.54422740
 179.0000000[ 4] score : 0.54453997
 179.0000000[ 5] score : 0.54449835
 179.0000000[ 6] score : 0.54401387
 179.0000000[ 7] score : 0.54445706
--------------------------------------
0.5429704645068041
   13 | 06m28s |    0.54297 |    1.1998 |    0.6242 | 


/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:335: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "


0.5367413065746067
 179.0000000[ 0] score : 0.53808684
 179.0000000[ 1] score : 0.54357253
 179.0000000[ 2] score : 0.54441501
 179.0000000[ 3] score : 0.54491139
 179.0000000[ 4] score : 0.54513420
 179.0000000[ 5] score : 0.54537554
 179.0000000[ 6] score : 0.54493263
 179.0000000[ 7] score : 0.54536094
--------------------------------------
0.5439736357710776
   14 | 06m35s |    0.54397 |    0.8725 |    0.5367 | 


/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:335: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "


1e-07
 179.0000000[ 0] score : 0.53777610
 179.0000000[ 1] score : 0.54301522
 179.0000000[ 2] score : 0.54415238
 179.0000000[ 3] score : 0.54494621
 179.0000000[ 4] score : 0.54531193
 179.0000000[ 5] score : 0.54542463
 179.0000000[ 6] score : 0.54495723
 179.0000000[ 7] score : 0.54530002
--------------------------------------
0.5438604650668455
   15 | 06m27s |    0.54386 |    1.2000 |    0.0000 | 


/home/watts/anaconda3/envs/tmlf/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:335: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "


In [41]:
# def run_dbscan():

data_dir = '../data/train'

#     event_ids = [
#             '000001030',##
#             '000001025','000001026','000001027','000001028','000001029',
#     ]

event_ids = [
        '000001030',##

]

sum=0
sum_score=0
for i,event_id in enumerate(event_ids):
    particles = pd.read_csv(data_dir + '/event%s-particles.csv'%event_id)
    hits  = pd.read_csv(data_dir + '/event%s-hits.csv'%event_id)
    cells = pd.read_csv(data_dir + '/event%s-cells.csv'%event_id)
    truth = pd.read_csv(data_dir + '/event%s-truth.csv'%event_id)
    particles = pd.read_csv(data_dir + '/event%s-particles.csv'%event_id)
    
    truth = pd.merge(truth, particles, how='left', on='particle_id')
    hits = pd.merge(hits, truth, how='left', on='hit_id')
    
    w1 = [0.9, 1.2]
    w2 = [0.3, 0.7]
    w3 = [0.1, 0.4]
    Niter = [140, 190]
    
    
    bo = BayesianOptimization(Fun4BO,pbounds = {'w1':w1,'w2':w2,'w3':w3,'Niter':Niter})
    bo.maximize(init_points = 5, n_iter = 10, acq = "ucb", kappa = 2.576)
    

Initialization
-----------------------------------------------------------------------------
 Step |   Time |      Value |     Niter |        w1 |        w2 |        w3 | 
181.08292172999705
181
1.1456102611664238 0.5296394986566276 0.22179061070177414 181
 179.0000000[ 0] score : 0.52563488
 179.0000000[ 1] score : 0.53229065
 179.0000000[ 2] score : 0.53413651
 179.0000000[ 3] score : 0.53383398
 179.0000000[ 4] score : 0.53460306
 179.0000000[ 5] score : 0.53559563
 179.0000000[ 6] score : 0.53429002
 179.0000000[ 7] score : 0.53487257
--------------------------------------
0.5331571620824995
    1 | 08m52s |    0.53316 |  181.0829 |    1.1456 |    0.5296 |    0.2218 | 
141.48002293021054
141
1.1061826474696426 0.4212020167074164 0.35069321952042953 141
 179.0000000[ 0] score : 0.51105303
 179.0000000[ 1] score : 0.51881890
 179.0000000[ 2] score : 0.52073978
 179.0000000[ 3] score : 0.52279146
 179.0000000[ 4] score : 0.52261981
 179.0000000[ 5] score : 0.52370021
 179.0000000[ 6] 

In [11]:
def do_dbscan_ensemble_hck(truth):
    
    #--------------------------------------------------------
    df = truth.copy()
    df = df.assign(r   = np.sqrt( df.x**2 + df.y**2))
    df = df.assign(d   = np.sqrt( df.x**2 + df.y**2 + df.z**2 ))
    df = df.assign(a   = np.arctan2(df.y, df.x))
    df = df.assign(cosa= np.cos(df.a))
    df = df.assign(sina= np.sin(df.a))
    df = df.assign(phi = np.arctan2(df.z, df.r))
    df = df.assign(momentum = np.sqrt( df.px**2 + df.py**2 + df.pz**2 ))
    df.loc[df.particle_id==0,'momentum']=0

    #df = df.loc[df.z>500] # consider dataset subset
    #df = df.loc[df.r<50 ] ## 0.04397/0.04750  (0.92569)

#     df = df.loc[df.z>500]
#     df = df.loc[(df.r>50) & (df.r<100)] ## 0.05259/0.05808  (0.90551)
    
    N = len(df)

    layer_id = df['layer_id'].values.astype(np.float32)
    momentum = df['momentum'].values.astype(np.float32)
    p = df[['particle_id']].values.astype(np.int64)
    x,y,z,r,a,cosa,sina,phi = df[['x', 'y', 'z', 'r', 'a', 'cosa', 'sina', 'phi']].values.astype(np.float32).T

    particle_ids = np.unique(p)
    particle_ids = particle_ids[particle_ids!=0]
    num_particle_ids = len(particle_ids)
    
    dj=0
    di=0
    EPS=1e-12
    #if 1:

    candidates = []
    for dj in np.arange(-20, 20+EPS, 10):
        for di in np.arange(-0.003, 0.003+EPS, 0.00025):
            ar = a +  di*r
            zr = (z+dj)/r  *0.1
            data2 = np.column_stack([ar,zr])

            _,l = dbscan(data2, eps=0.0025, min_samples=1,)
            track_ids = np.unique(l)
            track_ids = track_ids[track_ids!=0]
            neigbour = [ np.where(l==t)[0] for t in track_ids]

            unique,inverse,c = np.unique(l,return_counts=True,return_inverse=True)
            unique = unique[unique!=0]
            c = c[inverse]
            c[l==0] = 0

            for u in unique:
                candidate = np.where(l==u)[0]
                candidates.append(candidate)

    #---
    #<todo>
    #fix angle discontinunity problem here ...


    #-----
    #sort
    count = np.array([len(candidate) for candidate in candidates])
    sort = np.argsort(-count)
    candidates = [candidates[s] for s in sort]


    #show
    max_label=1
    label = np.zeros(N,np.int32)
    count = np.zeros(N,np.int32)

    for candidate in candidates:
        n = candidate
        L = len(n)
        #print(L)


        #---- filtering (secret sauce) ----------
        #if L<3: continue
        n = n[np.argsort(np.fabs(z[n]))]

        layer_id0 = layer_id[n[:-1]]
        layer_id1 = layer_id[n[1: ]]
        ld = layer_id1-layer_id0
        if np.any(ld>2): continue

        m = count[n].max()
        if L<m: continue

        #---- filtering ----------------------

        count[n]=L
        label[n]=max_label
        max_label += 1

    ##-###################################################################################3
    submission = pd.DataFrame(columns=['event_id', 'hit_id', 'track_id'],
        data=np.column_stack(([int(event_id),]*len(df), df.hit_id.values, label))
    ).astype(int)
    score1 = score_event(df, submission)
    

    #print results
    max_score = df.weight.sum()
    print('max_score = df.weight.sum() = %0.5f'%max_score)
    print('score1= %0.5f  (%0.5f)'%(score1*max_score,score1))
    
#     df = df.assign(r   = np.sqrt( df.x**2 + df.y**2))
#     df = df.assign(d   = np.sqrt( df.x**2 + df.y**2 + df.z**2 ))
#     df = df.assign(a   = np.arctan2(df.y, df.x))
#     df = df.assign(cosa= np.cos(df.a))
#     df = df.assign(sina= np.sin(df.a))
#     df = df.assign(phi = np.arctan2(df.z, df.r))
#     df = df.assign(momentum = np.sqrt( df.px**2 + df.py**2 + df.pz**2 ))
    
    df = df.drop(['r','d','a','cosa','sina','phi','momentum'], axis=1 )
    return df, label

In [12]:
# def run_dbscan():

data_dir = '../data/train'

#     event_ids = [
#             '000001030',##
#             '000001025','000001026','000001027','000001028','000001029',
#     ]

event_ids = [
        '000001030',##
]

sum=0
sum_score=0
for i,event_id in enumerate(event_ids):
    particles = pd.read_csv(data_dir + '/event%s-particles.csv'%event_id)
    hits  = pd.read_csv(data_dir + '/event%s-hits.csv'%event_id)
    cells = pd.read_csv(data_dir + '/event%s-cells.csv'%event_id)
    truth = pd.read_csv(data_dir + '/event%s-truth.csv'%event_id)
    particles = pd.read_csv(data_dir + '/event%s-particles.csv'%event_id)
    
    truth = pd.merge(truth, particles, how='left', on='particle_id')
    hits = pd.merge(hits, truth, how='left', on='hit_id')
#     truth = truth.merge(particles,  on=['particle_id'], how='left')
    
    hits1, l1 = do_dbscan_ensemble_hck(hits)
    
    hits1['track_id'] = l1
    
    submission = pd.DataFrame(columns=['event_id', 'hit_id', 'track_id'],
        data=np.column_stack(([int(event_id),]*len(hits1), hits1.hit_id.values, hits1['track_id'].values))
    ).astype(int)
    
    score = score_event(hits1, submission)
    i = 0
    print('[%2d] score : %0.8f'%(i, score))
        
    hits2 = hits[~hits.hit_id.isin(hits1.hit_id)]
#     w1 = [0.9, 1.2]
#     w2 = [0.3, 0.7]
#     w3 = [0.1, 0.4]
    
    w1 = [0.9, 1.2]
    w2 = [0.3, 0.8]
    w3 = [0.1, 0.4]
    w4 = [0.1, 0.8]
    
    Niter = [140, 190]
    
    l2 = do_dbscan_predict(hits2)
    hits2['track_id'] = l2
    submission = pd.DataFrame(columns=['event_id', 'hit_id', 'track_id'],
        data=np.column_stack(([int(event_id),]*len(hits2), hits2.hit_id.values, hits2['track_id'].values))
    ).astype(int)
    
    score = score_event(hits2, submission)
    i = 1
    print('[%2d] score : %0.8f'%(i, score))
     
    submission = pd.DataFrame(columns=['event_id', 'hit_id', 'track_id'],
        data=np.column_stack(([int(event_id),]*len(hits2), hits2.hit_id.values, hits2['track_id'].values))
    ).astype(int)
    for i in range(8):
        submission = extend(submission,hits2)
        score = score_event(truth, submission)
        print('[%2d] score : %0.8f'%(i, score))
        sum_score += score
        sum += 1

    
    print('--------------------------------------')
    print(sum_score/sum)

    hits = hits1.append(hits2)
    
    hits.sort_values('hit_id', inplace=True)
    
    track_id = hits['track_id'].values
    submission = pd.DataFrame(columns=['event_id', 'hit_id', 'track_id'],
        data=np.column_stack(([int(event_id),]*len(hits), hits.hit_id.values, track_id))
    ).astype(int)
    score = score_event(hits, submission)
    i = 2
    print('[%2d] score : %0.8f'%(i, score))
#     bo = BayesianOptimization(Fun4BO,pbounds = {'w1':w1,'w2':w2,'w3':w3,'w4':w4,'Niter':Niter})
#     bo.maximize(init_points = 3, n_iter = 20, acq = "ucb", kappa = 2.576)
    

max_score = df.weight.sum() = 1.00000
score1= 0.24221  (0.24221)
[ 0] score : 0.24221202


ValueError: Found array with 0 sample(s) (shape=(0, 4)) while a minimum of 1 is required by StandardScaler.

In [ ]:
hits = hits1.append(hits2)
hits.sort_values('hit_id', inplace=True)
    
track_id = hits['track_id'].values
hits['event_id'] = 1030
submission = pd.DataFrame(columns=['event_id', 'hit_id', 'track_id'],
    data=np.column_stack(([int(event_id),]*len(hits), hits.hit_id.values, track_id))
).astype(int)
print(submission.shape)
print(hits.shape)
for i in range(8):
    if i > 0:
        var1 = 1
    submission = extend(submission,hits)
    score = score_event(truth, submission)
    print('[%2d] score : %0.8f'%(i, score))
    sum_score += score
    sum += 1

print('--------------------------------------')
print(sum_score/sum)

In [69]:
submission.head()

event_id  hit_id  track_id
0      1030       1         0
1      1030       2  16907663
2      1030       3   8411454
3      1030       4  24229213
4      1030       5  16751177

In [68]:
hits.head()

hit_id        x         y       z  volume_id  layer_id  module_id  \
0       1 -60.8722  -2.90994 -1502.5          7         2          1   
1       2 -68.6209  -6.93030 -1502.5          7         2          1   
2       3 -64.5802   2.66632 -1502.5          7         2          1   
3       4 -88.7343  -7.35970 -1502.5          7         2          1   
4       5 -88.3262 -13.04520 -1502.5          7         2          1   

          particle_id       tx        ty    ...       weight        vx  \
0  427858663433043968 -60.8900  -2.93122    ...     0.000008  0.010578   
1  923241222145835008 -68.6150  -6.94011    ...     0.000008  0.012087   
2    4523734434054144 -64.5634   2.67475    ...     0.000006 -0.009604   
3  261225408500858880 -88.7490  -7.38212    ...     0.000012  0.001303   
4  743099023757410304 -88.3163 -13.05070    ...     0.000006 -0.011713   

         vy        vz        px        py        pz    q  nhits  track_id  
0 -0.000096  -2.68331 -0.396593 -0.000155  -9.72165 -1.0   12.0         0  
1 -0.023069  13.10000 -0.216069 -0.041984  -4.86522  1.0   13.0  16907663  
2  0.008012  -2.28776 -0.292098  0.031685  -6.75259 -1.0   16.0   8411454  
3  0.017286  -8.23350 -0.894095 -0.099110 -15.15630  1.0   14.0  24229213  
4 -0.011290  -5.07843 -0.283424 -0.068196  -4.91150  1.0   16.0  16751177  

[5 rows x 24 columns]

In [53]:
hits.shape

(113998, 24)

In [54]:
hits.T

0             1             2             3       \
hit_id       1.000000e+00  2.000000e+00  3.000000e+00  4.000000e+00   
x           -6.087220e+01 -6.862090e+01 -6.458020e+01 -8.873430e+01   
y           -2.909940e+00 -6.930300e+00  2.666320e+00 -7.359700e+00   
z           -1.502500e+03 -1.502500e+03 -1.502500e+03 -1.502500e+03   
volume_id    7.000000e+00  7.000000e+00  7.000000e+00  7.000000e+00   
layer_id     2.000000e+00  2.000000e+00  2.000000e+00  2.000000e+00   
module_id    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
particle_id  4.278587e+17  9.232412e+17  4.523734e+15  2.612254e+17   
tx          -6.089000e+01 -6.861500e+01 -6.456340e+01 -8.874900e+01   
ty          -2.931220e+00 -6.940110e+00  2.674750e+00 -7.382120e+00   
tz          -1.502500e+03 -1.502500e+03 -1.502500e+03 -1.502500e+03   
tpx         -3.898650e-01 -2.252430e-01 -2.847550e-01 -9.047950e-01   
tpy         -3.990320e-02 -3.876740e-03 -8.789220e-03 -4.921860e-02   
tpz         -9.717880e+00 -4.860310e+00 -6.747160e+00 -1.514960e+01   
weight       8.194570e-06  7.639430e-06  6.226490e-06  1.160100e-05   
vx           1.057850e-02  1.208670e-02 -9.604090e-03  1.303460e-03   
vy          -9.551550e-05 -2.306860e-02  8.011760e-03  1.728650e-02   
vz          -2.683310e+00  1.310000e+01 -2.287760e+00 -8.233500e+00   
px          -3.965930e-01 -2.160690e-01 -2.920980e-01 -8.940950e-01   
py          -1.545130e-04 -4.198390e-02  3.168540e-02 -9.911030e-02   
pz          -9.721650e+00 -4.865220e+00 -6.752590e+00 -1.515630e+01   
q           -1.000000e+00  1.000000e+00 -1.000000e+00  1.000000e+00   
nhits        1.200000e+01  1.300000e+01  1.600000e+01  1.400000e+01   
track_id     0.000000e+00  1.690766e+07  8.411454e+06  2.422921e+07   

                   4             5             6             7       \
hit_id       5.000000e+00  6.000000e+00  7.000000e+00  8.000000e+00   
x           -8.832620e+01 -6.308520e+01 -9.462820e+01 -7.685770e+01   
y           -1.304520e+01  8.780960e-01 -1.128420e+01 -3.215100e+00   
z           -1.502500e+03 -1.502500e+03 -1.502500e+03 -1.502500e+03   
volume_id    7.000000e+00  7.000000e+00  7.000000e+00  7.000000e+00   
layer_id     2.000000e+00  2.000000e+00  2.000000e+00  2.000000e+00   
module_id    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
particle_id  7.430990e+17  1.531238e+17  1.306098e+17  8.647023e+17   
tx          -8.831630e+01 -6.307700e+01 -9.462610e+01 -7.684700e+01   
ty          -1.305070e+01  8.722560e-01 -1.129730e+01 -3.193100e+00   
tz          -1.502500e+03 -1.502500e+03 -1.502500e+03 -1.502500e+03   
tpx         -2.955020e-01 -6.547260e-01 -6.140560e-01 -3.507220e-01   
tpy         -1.678430e-02 -1.131820e-02 -4.289640e-02 -3.452910e-02   
tpz         -4.905270e+00 -1.568480e+01 -9.641670e+00 -6.977570e+00   
weight       6.226490e-06  1.122110e-05  9.625210e-06  7.076740e-06   
vx          -1.171350e-02 -7.981130e-03  9.276720e-04 -1.541740e-03   
vy          -1.129040e-02 -2.732100e-02 -5.809210e-03 -1.421980e-02   
vz          -5.078430e+00  2.680370e-01 -7.066350e-01 -3.137180e+00   
px          -2.834240e-01 -6.608440e-01 -6.004640e-01 -3.615120e-01   
py          -6.819590e-02  2.946490e-02 -1.022950e-01  7.558940e-03   
pz          -4.911500e+00 -1.568790e+01 -9.651080e+00 -6.982060e+00   
q            1.000000e+00 -1.000000e+00  1.000000e+00 -1.000000e+00   
nhits        1.600000e+01  1.100000e+01  1.200000e+01  1.400000e+01   
track_id     1.675118e+07  1.745228e+07  1.721916e+07  2.454733e+07   

                   8             9           ...             113988  \
hit_id       9.000000e+00  1.000000e+01      ...       1.139890e+05   
x           -7.033050e+01 -7.952860e+01      ...      -7.833430e+02   
y           -1.388590e+01 -1.315530e+01      ...       7.238810e+01   
z           -1.502500e+03 -1.502500e+03      ...       2.944500e+03   
volume_id    7.000000e+00  7.000000e+00      ...       1.800000e+01   
layer_id     2.000000e+00  2.000000e+00  

In [ ]:
# def run_dbscan():

data_dir = '../data/train'

#     event_ids = [
#             '000001030',##
#             '000001025','000001026','000001027','000001028','000001029',
#     ]

event_ids = [
        '000001030',##

]

sum=0
sum_score=0
for i,event_id in enumerate(event_ids):
    particles = pd.read_csv(data_dir + '/event%s-particles.csv'%event_id)
    hits  = pd.read_csv(data_dir + '/event%s-hits.csv'%event_id)
    cells = pd.read_csv(data_dir + '/event%s-cells.csv'%event_id)
    truth = pd.read_csv(data_dir + '/event%s-truth.csv'%event_id)
    particles = pd.read_csv(data_dir + '/event%s-particles.csv'%event_id)
    
    truth = pd.merge(truth, particles, how='left', on='particle_id')
    hits = pd.merge(hits, truth, how='left', on='hit_id')
    
    w1 = [0.9, 1.2]
    w2 = [0.3, 0.7]
    w3 = [0.1, 0.4]
    Niter = [140, 190]
    
    
    bo = BayesianOptimization(Fun4BO,pbounds = {'w1':w1,'w2':w2,'w3':w3,'Niter':Niter})
    bo.maximize(init_points = 3, n_iter = 20, acq = "ucb", kappa = 2.576)
    

Initialization
-----------------------------------------------------------------------------
 Step |   Time |      Value |     Niter |        w1 |        w2 |        w3 | 
184.7827709130419
184
1.0561046005761139 0.5351622558071004 0.3762123539827661 184
 179.0000000[ 0] score : 0.53942962
 179.0000000[ 1] score : 0.54606243
 179.0000000[ 2] score : 0.54780086
 179.0000000[ 3] score : 0.54875295
 179.0000000[ 4] score : 0.54815666
 179.0000000[ 5] score : 0.54860441
 179.0000000[ 6] score : 0.54801785
 179.0000000[ 7] score : 0.54881484
--------------------------------------
0.5469549540012781
    1 | 05m08s |    0.54695 |  184.7828 |    1.0561 |    0.5352 |    0.3762 | 
145.0794227877262
145
1.1353520277193074 0.658195945930628 0.24032322705809864 145
 179.0000000[ 0] score : 0.52382250
 179.0000000[ 1] score : 0.52837456
 179.0000000[ 2] score : 0.53034994
 179.0000000[ 3] score : 0.53139514
 179.0000000[ 4] score : 0.53153080
 179.0000000[ 5] score : 0.53243534
 179.0000000[ 6] scor

 179.0000000[ 2] score : 0.45956269
 179.0000000[ 3] score : 0.46153693
 179.0000000[ 4] score : 0.46225305
 179.0000000[ 5] score : 0.46312552
 179.0000000[ 6] score : 0.46227716
 179.0000000[ 7] score : 0.46323152
--------------------------------------
0.46055974873573446
   17 | 05m21s |    0.46056 |  186.4388 |    1.2000 |    0.3000 |    0.1000 | 
175.93802446513746
175
1.2 0.7 0.4 175
 179.0000000[ 0] score : 0.52847339
 179.0000000[ 1] score : 0.53424707
 179.0000000[ 2] score : 0.53617756
 179.0000000[ 3] score : 0.53704935
 179.0000000[ 4] score : 0.53663841
 179.0000000[ 5] score : 0.53773147
 179.0000000[ 6] score : 0.53728202
 179.0000000[ 7] score : 0.53720027
--------------------------------------
0.5355999427729057
   18 | 05m21s |    0.53560 |  175.9380 |    1.2000 |    0.7000 |    0.4000 | 
164.75000708655898
164
0.9 0.7 0.4 164
 179.0000000[ 0] score : 0.52636347
 179.0000000[ 1] score : 0.53308124
 179.0000000[ 2] score : 0.53533614
 179.0000000[ 3] score : 0.53587774

In [49]:
w1 = 1.0561046005761139
w2 = 0.5351622558071004
w3 = 0.3762123539827661
Niter = 184

# 172.3593 |    1.0579 |    0.5147 |    0.3853

In [50]:
def run_make_submission():

    data_dir = '../data/test'


    tic = t = time.time()
    event_ids = [ '%09d'%i for i in range(0,125) ]  #(0,125)

    if 1:
        submissions = []
        for i,event_id in enumerate(event_ids):
            hits  = pd.read_csv(data_dir + '/event%s-hits.csv'%event_id)
            cells = pd.read_csv(data_dir + '/event%s-cells.csv'%event_id)

            track_id = trackML2(hits, w1, w2, w3, Niter)
            #track_id = back_fit(track_id,hits)

            toc =  time.time()
            print('\revent_id : %s  , %0.0f min'%(event_id, (toc-tic)/60))

            # Prepare submission for an event
            submission = pd.DataFrame(columns=['event_id', 'hit_id', 'track_id'],
                data=np.column_stack(([event_id,]*len(hits), hits.hit_id.values, track_id))
            ).astype(int)
            submissions.append(submission)
            
            for i in range(8):
                submission = extend(submission,hits)
            
            
            submission.to_csv('../cache/sub2/%s.csv.gz'%event_id,
                                index=False, compression='gzip')

            #------------------------------------------------------
    if 1:

        event_ids = [ '%09d'%i for i in range(0,125) ]  #(0,125)
        submissions = []
        for i,event_id in enumerate(event_ids):
            submission  = pd.read_csv('../cache/sub2/%s.csv.gz'%event_id, compression='gzip')
            submissions.append(submission)

        
        # Create submission file
        submission = pd.concat(submissions, axis=0)
        submission.to_csv('../submissions/sub2/submission-0016.csv.gz',
                            index=False, compression='gzip')
        print(len(submission))

In [51]:
run_make_submission()

event_id : 000000000  , 3 min
event_id : 000000001  , 8 min
event_id : 000000002  , 13 min
event_id : 000000003  , 18 min
event_id : 000000004  , 24 min
event_id : 000000005  , 29 min
event_id : 000000006  , 34 min
event_id : 000000007  , 39 min
event_id : 000000008  , 44 min
event_id : 000000009  , 50 min
event_id : 000000010  , 55 min
event_id : 000000011  , 60 min
event_id : 000000012  , 65 min
event_id : 000000013  , 70 min
event_id : 000000014  , 75 min
event_id : 000000015  , 80 min
event_id : 000000016  , 84 min
event_id : 000000017  , 89 min
event_id : 000000018  , 95 min
event_id : 000000019  , 99 min
event_id : 000000020  , 104 min
event_id : 000000021  , 108 min
event_id : 000000022  , 113 min
event_id : 000000023  , 119 min
event_id : 000000024  , 124 min
event_id : 000000025  , 129 min
event_id : 000000026  , 134 min
event_id : 000000027  , 138 min
event_id : 000000028  , 143 min
event_id : 000000029  , 148 min
event_id : 000000030  , 152 min
event_id : 000000031  , 157 mi